-- ============================================================================
-- GVSI SLI Tracker — Supabase schema (project: GVSI NetPulse,
-- ref fsebdacptgoknbjqdlor, region ap-northeast-2)
--
-- This file is the repo's record of what is applied to the project. It was applied
-- through the Supabase migration tooling as:
--
--   sli_archive_auth_sessions   -- tables, RLS, functions, grants, the view
--   fix_maintenance_set_upsert  -- ON CONFLICT may only use the bare table name
--   maintenance_set_json_null_guard -- JSON null is not SQL NULL; see maintenance_set
--   hardening_advisor_fixes     -- see the end of this file
--   archive_public_read         -- anon may READ the two archive tables; see the end
--   sme_collections_columns     -- GROSS / NET for SME's MRC block; see the archive tables
--
-- Two jobs live here:
--
--   1. COLD ARCHIVE  — closed months move out of the Google Sheet into
--      `sli_raw_daily` + `sli_mtd`, so the spreadsheet stops growing forever.
--      Written by the Apps Script archive job with the service_role key.
--
--   2. ACCESS        — `sli_users`/`sli_sessions`/`sli_settings` replace the publicly
--      readable Login Credentials sheet, and give the app session tokens, presence and
--      the maintenance switch.
--
-- Access model: the app is a static site holding only the PUBLIC anon key, so every
-- table has RLS on with NO anonymous policy. All reads and writes go through
-- SECURITY DEFINER functions; the privileged ones check the caller's session token
-- inside Postgres (the token IS the credential — the browser cannot assert a role).
-- ============================================================================

-- ---------------------------------------------------------------- raw daily --
create table if not exists public.sli_raw_daily (
  id bigint generated by default as identity primary key,
  plan text not null,                   -- 'fiberx' | 'bida' | 'sme'
  month_key text not null,              -- '2026-09'
  report_date date not null,
  date_label text not null,             -- 'September 1, 2026' — the app's date key
  area text not null,
  is_overall_total boolean not null default false,
  bf numeric, inc numeric, total_jo numeric,
  comp_from_total numeric, comp_from_rjo numeric, total_completed numeric,
  rjo_incoming numeric, rjo_redispatched numeric, total_rjo numeric,
  carry_over numeric, mtd numeric, gross numeric, net numeric, target numeric,
  pct text,                             -- text: preserves '#DIV/0!' verbatim
  -- gross / net are SME's MRC collection (the sheet's L and M). BIDA and FIBERX have no
  -- such columns, so their rows store NULL rather than a zero that would read as a figure
  -- nobody collected. `target` is a peso figure on SME and a ticket count elsewhere.
  row_order integer,
  archived_at timestamptz not null default now(),
  constraint sli_raw_daily_key unique (plan, report_date, area)
);
create index if not exists sli_raw_daily_plan_month_idx on public.sli_raw_daily (plan, month_key);

-- -------------------------------------------------------------------- mtd ----
create table if not exists public.sli_mtd (
  id bigint generated by default as identity primary key,
  plan text not null,
  month_key text not null,
  month_label text not null,            -- 'September 2026'
  area text not null,
  is_overall_total boolean not null default false,
  comp_from_total numeric, comp_from_rjo numeric, total_completed numeric,
  this_mo_rjo numeric, prev_mos_rjo numeric, total_rjo numeric,
  last_mtd numeric, gross numeric, net numeric, target numeric, total_incoming numeric,
  -- gross / net: SME only, same as sli_raw_daily. NULL on BIDA and FIBERX.
  last_pct text,
  row_order integer,
  archived_at timestamptz not null default now(),
  constraint sli_mtd_key unique (plan, month_key, area)
);
create index if not exists sli_mtd_plan_month_idx on public.sli_mtd (plan, month_key);
create index if not exists sli_mtd_plan_total_idx on public.sli_mtd (plan, is_overall_total);

-- The `OVER ALL TOTAL` row is archived VERBATIM, never recomputed: it is not always
-- the sum of the area rows (BIDA August: total 387 vs area sum 370), and it is the
-- number the dashboard showed when that month was live.

-- ------------------------------------------------------------------ users ----
create table if not exists public.sli_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,          -- lowercase SHA-256 hex (unchanged scheme)
  full_name text,
  role text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- --------------------------------------------------------------- sessions ----
create table if not exists public.sli_sessions (
  token uuid primary key default gen_random_uuid(),
  username text not null,
  full_name text,
  role text,
  plan text,
  view text,
  user_agent text,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  revoked_at timestamptz
);
create index if not exists sli_sessions_last_seen_idx on public.sli_sessions (last_seen_at desc);
create index if not exists sli_sessions_username_idx on public.sli_sessions (username);

-- --------------------------------------------------------------- settings ----
create table if not exists public.sli_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

-- --------------------------------------------------- lock tables down (RLS) --
alter table public.sli_raw_daily enable row level security;
alter table public.sli_mtd       enable row level security;
alter table public.sli_users     enable row level security;
alter table public.sli_sessions  enable row level security;
alter table public.sli_settings  enable row level security;

-- No policies on purpose for these three: nothing here is publicly readable. A request
-- with the anon key gets 401 "permission denied for table sli_users".
--
-- The two ARCHIVE tables are the exception, applied at the end of this file: the app
-- reads closed months straight from Supabase with the public anon key, so they carry a
-- SELECT-only read policy while every write still requires service_role.
revoke all on public.sli_raw_daily from anon, authenticated;
revoke all on public.sli_mtd       from anon, authenticated;
revoke all on public.sli_users     from anon, authenticated;
revoke all on public.sli_sessions  from anon, authenticated;
revoke all on public.sli_settings  from anon, authenticated;

grant all on public.sli_raw_daily to service_role;
grant all on public.sli_mtd       to service_role;
grant all on public.sli_users     to service_role;
grant all on public.sli_sessions  to service_role;
grant all on public.sli_settings  to service_role;

-- ------------------------------------------------------------------- view ----
create or replace view public.sli_active_users as
select token, username, full_name, role, plan, view, started_at, last_seen_at,
       extract(epoch from (now() - started_at))::bigint as active_seconds
from public.sli_sessions
where ended_at is null
  and revoked_at is null
  and last_seen_at > now() - interval '2 minutes';

-- ============================================================== functions ====

create or replace function public.sli_is_developer(p_token uuid)
returns boolean
language sql security definer set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.sli_sessions s
    where s.token = p_token
      and s.ended_at is null
      and s.revoked_at is null
      and lower(trim(coalesce(s.role, ''))) = 'developer'
  );
$$;

-- ------------------------------------------------------------------ login ----
-- Empty result = wrong credentials. A match opens a session row and returns its token.
create or replace function public.verify_login(p_username text, p_hash text, p_user_agent text default null)
returns table (token uuid, username text, full_name text, role text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user public.sli_users%rowtype;
  v_token uuid;
begin
  select * into v_user from public.sli_users u
  where lower(trim(u.username)) = lower(trim(coalesce(p_username, '')))
    and u.password_hash = lower(trim(coalesce(p_hash, '')))
    and u.is_active
  limit 1;

  if not found then
    return;
  end if;

  insert into public.sli_sessions (username, full_name, role, user_agent)
  values (v_user.username, v_user.full_name, v_user.role, p_user_agent)
  returning sli_sessions.token into v_token;

  return query select v_token, v_user.username, v_user.full_name, v_user.role;
end;
$$;

-- ---------------------------------------------------------------- presence ----
-- One call per heartbeat: records presence, answers "is my token still valid?" and
-- hands back the maintenance state.
create or replace function public.presence_ping(p_token uuid, p_plan text default null, p_view text default null)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_session public.sli_sessions%rowtype;
  v_maintenance jsonb;
  v_valid boolean := false;
  v_user public.sli_users%rowtype;
begin
  select * into v_session from public.sli_sessions s where s.token = p_token;

  if found and v_session.ended_at is null and v_session.revoked_at is null then
    -- A user deactivated mid-session is treated as revoked.
    select * into v_user from public.sli_users u where lower(u.username) = lower(v_session.username);
    if found and v_user.is_active then
      v_valid := true;
      update public.sli_sessions s
         set last_seen_at = now(),
             plan = coalesce(p_plan, s.plan),
             view = coalesce(p_view, s.view)
       where s.token = p_token;
    else
      update public.sli_sessions s set revoked_at = coalesce(s.revoked_at, now()) where s.token = p_token;
    end if;
  end if;

  v_maintenance := public.maintenance_get();

  return jsonb_build_object('token_valid', v_valid, 'maintenance', v_maintenance);
end;
$$;

create or replace function public.presence_leave(p_token uuid)
returns void
language sql security definer set search_path = public, pg_temp as $$
  update public.sli_sessions s
     set ended_at = coalesce(s.ended_at, now())
   where s.token = p_token;
$$;

-- ------------------------------------------------------------- maintenance ----
-- Public: the login screen and every signed-out visitor needs this. An expired flag
-- reads as disabled, so a forgotten switch can never lock the team out.
create or replace function public.maintenance_get()
returns jsonb
language sql security definer set search_path = public, pg_temp as $$
  select coalesce(
    (select case
       when (s.value->>'enabled')::boolean is not true then
         jsonb_build_object('enabled', false)
       when s.value ? 'expires_at'
         and (s.value->>'expires_at') <> ''
         and (s.value->>'expires_at')::timestamptz <= now() then
         jsonb_build_object('enabled', false, 'expired', true,
                            'since', s.value->'since', 'by', s.value->'by')
       else
         jsonb_build_object('enabled', true,
                            'message', s.value->'message',
                            'since', s.value->'since',
                            'by', s.value->'by',
                            'expires_at', s.value->'expires_at')
     end
     from public.sli_settings s where s.key = 'maintenance'),
    jsonb_build_object('enabled', false)
  );
$$;

create or replace function public.maintenance_set(p_token uuid, p_enabled boolean,
                                                 p_message text default null,
                                                 p_expires_at timestamptz default null)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_row public.sli_sessions%rowtype;
  v_on boolean := coalesce(p_enabled, false);
  v_existing jsonb;
begin
  if not public.sli_is_developer(p_token) then
    raise exception 'not authorized: developer session required' using errcode = '42501';
  end if;

  select * into v_row from public.sli_sessions s where s.token = p_token;
  select value into v_existing from public.sli_settings where key = 'maintenance';

  -- jsonb_build_object() stores a SQL NULL as a JSON null, and `value->'since'` then
  -- returns that JSON null (NOT SQL NULL), so a plain coalesce() would keep the empty
  -- value forever after the first off-transition — the panel would read "Ni — noong —"
  -- and nobody would know who locked the app. Reuse a stored value only when it is an
  -- actual string; otherwise stamp a fresh one.
  insert into public.sli_settings (key, value, updated_at, updated_by)
  values ('maintenance', jsonb_build_object(
            'enabled', v_on,
            'message', nullif(trim(coalesce(p_message, '')), ''),
            'expires_at', case when v_on then p_expires_at else null end,
            'since', case when v_on then to_jsonb(now()) else null end,
            'by', case when v_on then to_jsonb(v_row.username) else null end
          ), now(), v_row.username)
  on conflict (key) do update
     set value = jsonb_build_object(
           'enabled', v_on,
           'message', nullif(trim(coalesce(p_message, '')), ''),
           'expires_at', case when v_on then p_expires_at else null end,
           -- "since"/"by" stay sticky while the switch is on, so editing the message
           -- does not erase who turned it on.
           'since', case when v_on and jsonb_typeof(v_existing->'since') = 'string'
                         then v_existing->'since'
                         when v_on then to_jsonb(now()) else null end,
           'by', case when v_on and jsonb_typeof(v_existing->'by') = 'string'
                      then v_existing->'by'
                      when v_on then to_jsonb(v_row.username) else null end
         ),
         updated_at = now(),
         updated_by = v_row.username;

  return public.maintenance_get();
end;
$$;

-- ------------------------------------------------------------------- admin ----
create or replace function public.active_users(p_token uuid)
returns table (username text, full_name text, role text, plan text, view text,
               started_at timestamptz, last_seen_at timestamptz, active_seconds bigint)
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.sli_is_developer(p_token) then
    raise exception 'not authorized: developer session required' using errcode = '42501';
  end if;

  return query
    select a.username, a.full_name, a.role, a.plan, a.view,
           a.started_at, a.last_seen_at, a.active_seconds
    from public.sli_active_users a
    order by a.started_at asc;
end;
$$;

create or replace function public.recent_sessions(p_token uuid, p_limit integer default 25)
returns table (username text, full_name text, role text, started_at timestamptz,
               last_seen_at timestamptz, ended_at timestamptz, revoked_at timestamptz,
               duration_seconds bigint)
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.sli_is_developer(p_token) then
    raise exception 'not authorized: developer session required' using errcode = '42501';
  end if;

  return query
    select s.username, s.full_name, s.role, s.started_at, s.last_seen_at,
           s.ended_at, s.revoked_at,
           extract(epoch from (coalesce(s.ended_at, s.last_seen_at) - s.started_at))::bigint
    from public.sli_sessions s
    order by s.started_at desc
    limit greatest(1, least(coalesce(p_limit, 25), 200));
end;
$$;

create or replace function public.force_signout_all(p_token uuid, p_keep_self boolean default true)
returns integer
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_count integer;
begin
  if not public.sli_is_developer(p_token) then
    raise exception 'not authorized: developer session required' using errcode = '42501';
  end if;

  update public.sli_sessions s
     set revoked_at = now()
   where s.revoked_at is null
     and s.ended_at is null
     and (not coalesce(p_keep_self, true) or s.token <> p_token);

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------- grants -----
-- Every RPC is callable with the public anon key; the privileged ones authorize by
-- checking the session token's role inside the function.
grant execute on function public.verify_login(text, text, text) to anon, authenticated;
grant execute on function public.presence_ping(uuid, text, text) to anon, authenticated;
grant execute on function public.presence_leave(uuid) to anon, authenticated;
grant execute on function public.maintenance_get() to anon, authenticated;
grant execute on function public.maintenance_set(uuid, boolean, text, timestamptz) to anon, authenticated;
grant execute on function public.active_users(uuid) to anon, authenticated;
grant execute on function public.recent_sessions(uuid, integer) to anon, authenticated;
grant execute on function public.force_signout_all(uuid, boolean) to anon, authenticated;
-- ============================================================================
-- hardening_advisor_fixes — found by the Supabase security advisors, not by code
-- review. Two default grants in Supabase made more public than intended:
--
--   1. New views in `public` inherit SELECT for anon/authenticated, so
--      `sli_active_users` returned the live roster to anyone holding the (public)
--      anon key. Confirmed with a real request, then closed.
--   2. `revoke ... from anon` is not enough for a function: every role is a member of
--      PUBLIC, which holds the default EXECUTE grant. `sli_is_developer` therefore
--      stayed callable and had to be revoked FROM PUBLIC.
--
-- The advisor reports RLS-enabled-no-policy on all five tables as INFO. That is the
-- intended state: no policy means nothing is publicly readable, and all app access
-- goes through the functions above.
-- ============================================================================

revoke all on public.sli_active_users from anon, authenticated;
alter view public.sli_active_users set (security_invoker = true);

revoke execute on function public.sli_is_developer(uuid) from public, anon, authenticated;

-- ============================================================================
-- archive_public_read — the app reads CLOSED months directly from Supabase
--
-- Unlike everything above, these two tables have to be readable WITHOUT a session: the
-- browser holds only the public anon key, and a closed month is fetched from here
-- instead of from the spreadsheet.
--
-- The `revoke all ... from anon` earlier in this file was the right call for the access
-- tables and the wrong one for the archive — it broke archived months in the app (401
-- on every read, silently falling back to sheet-only) until this was applied. It is
-- recorded here so that re-running this file on a fresh project cannot repeat that.
--
-- Read only. INSERT/UPDATE/DELETE stay service_role-only, which is what stops a
-- browser-side bug from corrupting a closed month, and what the Apps Script's
-- 'Test Supabase Connection' verifies before the archive job is switched on.
-- ============================================================================

grant select on public.sli_raw_daily to anon, authenticated;
grant select on public.sli_mtd       to anon, authenticated;

drop policy if exists sli_raw_daily_read on public.sli_raw_daily;
create policy sli_raw_daily_read on public.sli_raw_daily
  for select to anon, authenticated using (true);

drop policy if exists sli_mtd_read on public.sli_mtd;
create policy sli_mtd_read on public.sli_mtd
  for select to anon, authenticated using (true);
