-- ============================================================================
-- sli_targets — the year’s target plan, copied out of the shared `TARGET 2026` tab
--
-- Generated by `scripts/targets-seed.cjs` from the `TARGET 2026` (gid 1221052795)
-- export of the shared workbook: 3 plans x 12 months x 13 provinces,
-- in the tab’s own province order. This file is a migration, not something the app runs:
-- the dashboard reads `sli_targets` and never the tab. Regenerate and re-run it to move
-- the plan to a new year, or after a target has been corrected in the sheet.
--
-- The annual target is NOT stored. The app sums the twelve monthly rows, which is the
-- same figure the tab prints in its TOTAL column — this generator refuses to emit a row
-- whose months do not add up to that column, so the two cannot disagree.
--
-- Re-running replaces the plan with this file’s version of it, month by month, area by
-- area: the tab is the source the plan is copied FROM, and this file is that copy.
-- ============================================================================

insert into public.sli_targets
  (plan, month_key, month_label, area, target, row_order, source, updated_at)
select t.plan, m.month_key, m.month_label, t.area, m.target::numeric, t.row_order,
       'worksheet', now()
from (values
  -- BIDA — annual target 11,059,
  ('bida', 'Benguet', 0, 58, 53, 58, 53, 58, 60, 64, 58, 64, 67, 60, 62),
  ('bida', 'Mountain Province', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),
  ('bida', 'Ilocos Sur', 2, 127, 117, 131, 118, 127, 134, 139, 132, 139, 150, 133, 136),
  ('bida', 'Ilocos Norte', 3, 178, 162, 176, 158, 173, 178, 187, 176, 187, 199, 178, 183),
  ('bida', 'Abra', 4, 15, 13, 15, 14, 15, 16, 16, 15, 16, 17, 16, 16),
  ('bida', 'Nueva Vizcaya', 5, 84, 76, 85, 77, 84, 87, 90, 86, 90, 97, 86, 88),
  ('bida', 'Ifugao', 6, 23, 21, 24, 21, 23, 26, 26, 24, 26, 27, 24, 26),
  ('bida', 'Isabela', 7, 186, 171, 180, 162, 176, 183, 190, 180, 190, 204, 181, 188),
  ('bida', 'Quirino', 8, 18, 17, 18, 17, 8, 18, 20, 18, 20, 21, 18, 19),
  ('bida', 'Aurora', 9, 0, 0, 0, 0, 0, 0, 0, 25, 26, 28, 25, 26),
  ('bida', 'Cagayan', 10, 254, 227, 315, 284, 310, 331, 352, 332, 0, 0, 0, 0),
  ('bida', 'Kalinga', 11, 20, 19, 21, 19, 20, 21, 22, 21, 0, 0, 0, 0),
  ('bida', 'Apayao', 12, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0),
  -- FIBERX — annual target 30,466,
  ('fiberx', 'Benguet', 0, 848, 763, 1019, 763, 1019, 932, 848, 509, 509, 425, 429, 429),
  ('fiberx', 'Mountain Province', 1, 26, 24, 31, 24, 31, 28, 26, 15, 15, 13, 13, 13),
  ('fiberx', 'Ilocos Sur', 2, 439, 395, 528, 395, 528, 481, 439, 265, 265, 219, 219, 219),
  ('fiberx', 'Ilocos Norte', 3, 492, 444, 590, 444, 590, 544, 492, 296, 296, 248, 248, 248),
  ('fiberx', 'Abra', 4, 71, 65, 86, 65, 86, 79, 71, 43, 43, 37, 37, 37),
  ('fiberx', 'Nueva Vizcaya', 5, 262, 234, 313, 234, 321, 292, 280, 222, 184, 180, 221, 180),
  ('fiberx', 'Ifugao', 6, 40, 36, 48, 36, 48, 48, 41, 24, 39, 26, 26, 116),
  ('fiberx', 'Isabela', 7, 412, 370, 493, 370, 493, 503, 428, 265, 265, 224, 216, 216),
  ('fiberx', 'Quirino', 8, 64, 57, 75, 57, 75, 69, 64, 38, 38, 31, 31, 31),
  ('fiberx', 'Aurora', 9, 0, 0, 0, 0, 0, 0, 0, 95, 83, 83, 85, 83),
  ('fiberx', 'Cagayan', 10, 281, 254, 340, 254, 384, 366, 299, 239, 0, 0, 0, 0),
  ('fiberx', 'Kalinga', 11, 46, 42, 56, 42, 56, 51, 46, 28, 0, 0, 0, 0),
  ('fiberx', 'Apayao', 12, 16, 13, 18, 13, 18, 18, 16, 9, 0, 0, 0, 0),
  -- SME — annual target 4,844,391,
  ('sme', 'Benguet', 0, 74126, 88866, 98198, 63406, 62164, 69149, 67027, 65091, 62098, 51906, 47835, 46611),
  ('sme', 'Mountain Province', 1, 10580, 12685, 13104, 8996, 9909, 9871, 9568, 9291, 8864, 7409, 6828, 6653),
  ('sme', 'Ilocos Sur', 2, 63775, 76456, 75783, 54605, 66981, 59492, 57667, 56002, 53427, 44658, 41155, 40102),
  ('sme', 'Ilocos Norte', 3, 54718, 65598, 64566, 46905, 51243, 51043, 49478, 48048, 45839, 38316, 35311, 34407),
  ('sme', 'Abra', 4, 11424, 13695, 14147, 9712, 10698, 10657, 10330, 10031, 9570, 7999, 7372, 7183),
  ('sme', 'Nueva Vizcaya', 5, 26025, 35774, 41165, 41682, 45913, 45734, 44331, 43050, 41071, 34330, 31637, 30827),
  ('sme', 'Ifugao', 6, 13692, 16415, 16957, 11641, 12823, 12773, 12381, 12023, 11471, 9588, 8836, 8610),
  ('sme', 'Isabela', 7, 97737, 112598, 113748, 75021, 76903, 76903, 74769, 72609, 64399, 59759, 54738, 55228),
  ('sme', 'Quirino', 8, 12880, 15441, 15951, 10951, 12062, 12015, 11647, 11310, 10790, 9019, 8838, 8099),
  ('sme', 'Aurora', 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  ('sme', 'Cagayan', 10, 84822, 101689, 103407, 60638, 72526, 71943, 69511, 67503, 0, 0, 0, 0),
  ('sme', 'Kalinga', 11, 14505, 17389, 17963, 12332, 13584, 13531, 13116, 12737, 0, 0, 0, 0),
  ('sme', 'Apayao', 12, 13402, 16067, 16598, 11395, 12551, 12502, 12119, 11769, 0, 0, 0, 0)
) as t (plan, area, row_order, jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec)
cross join lateral (values
  ('2026-01', 'January 2026', t.jan),
  ('2026-02', 'February 2026', t.feb),
  ('2026-03', 'March 2026', t.mar),
  ('2026-04', 'April 2026', t.apr),
  ('2026-05', 'May 2026', t.may),
  ('2026-06', 'June 2026', t.jun),
  ('2026-07', 'July 2026', t.jul),
  ('2026-08', 'August 2026', t.aug),
  ('2026-09', 'September 2026', t.sep),
  ('2026-10', 'October 2026', t.oct),
  ('2026-11', 'November 2026', t.nov),
  ('2026-12', 'December 2026', t.dec)
) as m (month_key, month_label, target)
on conflict (plan, month_key, area) do update set
  month_label = excluded.month_label,
  target = excluded.target,
  row_order = excluded.row_order,
  source = excluded.source,
  updated_at = excluded.updated_at;

