/**
 * Service Plan Configuration
 * 
 * Each plan maps to a separate Google Sheet with identical internal structure:
 *   - FIBERX NEW REPORT tab (source data)
 *   - RAW DATA tab (continuous format, imported by Apps Script)
 *   - MTD tab (monthly summary, generated by Apps Script)
 *
 * To add a new plan: add an entry here + create the Google Sheet + copy Apps Script.
 */

const SHEET_BASE = 'https://docs.google.com/spreadsheets/d/'

export const PLANS = {
  fiberx: {
    id: 'fiberx',
    name: 'FIBERX',
    fullName: 'FiberX Service Line',
    color: 'indigo',
    accentHex: '#4A1FB8',
    accentClasses: {
      bg: 'bg-indigo-600',
      hover: 'hover:bg-indigo-500',
      text: 'text-indigo-600 dark:text-indigo-400',
      ring: 'ring-indigo-500/30',
      badge: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300 border-indigo-200 dark:border-indigo-700/40',
    },
    mtdUrl: `${SHEET_BASE}1UUd8cpfKeOCBHANx9wmM7l1apFyDoZRv0dHZa2_bVr0/export?format=csv&gid=1061751267`,
    rawUrl: `${SHEET_BASE}1UUd8cpfKeOCBHANx9wmM7l1apFyDoZRv0dHZa2_bVr0/export?format=csv&gid=486719298`,
    sheetId: '1UUd8cpfKeOCBHANx9wmM7l1apFyDoZRv0dHZa2_bVr0',
  },
  bida: {
    id: 'bida',
    name: 'BIDA',
    fullName: 'BIDA Service Line',
    color: 'red',
    accentHex: '#D32F2F',
    accentClasses: {
      bg: 'bg-red-600',
      hover: 'hover:bg-red-500',
      text: 'text-red-600 dark:text-red-400',
      ring: 'ring-red-500/30',
      badge: 'bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300 border-red-200 dark:border-red-700/40',
    },
    mtdUrl: `${SHEET_BASE}1FrEowZ9Zl0jMAyLDe4OZE2cQV04nIz-rjRkLi6uv99M/export?format=csv&gid=1061751267`,
    rawUrl: `${SHEET_BASE}1FrEowZ9Zl0jMAyLDe4OZE2cQV04nIz-rjRkLi6uv99M/export?format=csv&gid=486719298`,
    sheetId: '1FrEowZ9Zl0jMAyLDe4OZE2cQV04nIz-rjRkLi6uv99M',
  },
  sme: {
    id: 'sme',
    name: 'SME',
    fullName: 'SME Service Line',
    color: 'teal',
    accentHex: '#00897B',
    accentClasses: {
      bg: 'bg-teal-600',
      hover: 'hover:bg-teal-500',
      text: 'text-teal-600 dark:text-teal-400',
      ring: 'ring-teal-500/30',
      badge: 'bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300 border-teal-200 dark:border-teal-700/40',
    },
    mtdUrl: `${SHEET_BASE}10P3GatvwC76IujPpjHtqgyNjE71ChAoP_8Ln7BDcvTY/export?format=csv&gid=1061751267`,
    rawUrl: `${SHEET_BASE}10P3GatvwC76IujPpjHtqgyNjE71ChAoP_8Ln7BDcvTY/export?format=csv&gid=486719298`,
    sheetId: '10P3GatvwC76IujPpjHtqgyNjE71ChAoP_8Ln7BDcvTY',
  },
}

export const PLAN_ORDER = ['fiberx', 'bida', 'sme']
export const DEFAULT_PLAN = 'fiberx'
